/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SearchService } from "../search.service";
import { SearchCreateInput } from "./SearchCreateInput";
import { Search } from "./Search";
import { SearchFindManyArgs } from "./SearchFindManyArgs";
import { SearchWhereUniqueInput } from "./SearchWhereUniqueInput";
import { SearchUpdateInput } from "./SearchUpdateInput";

export class SearchControllerBase {
  constructor(protected readonly service: SearchService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Search })
  async createSearch(@common.Body() data: SearchCreateInput): Promise<Search> {
    return await this.service.createSearch({
      data: data,
      select: {
        createdAt: true,
        id: true,
        searchedAt: true,
        searchResults: true,
        strainName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Search] })
  @ApiNestedQuery(SearchFindManyArgs)
  async searches(@common.Req() request: Request): Promise<Search[]> {
    const args = plainToClass(SearchFindManyArgs, request.query);
    return this.service.searches({
      ...args,
      select: {
        createdAt: true,
        id: true,
        searchedAt: true,
        searchResults: true,
        strainName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Search })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async search(
    @common.Param() params: SearchWhereUniqueInput
  ): Promise<Search | null> {
    const result = await this.service.search({
      where: params,
      select: {
        createdAt: true,
        id: true,
        searchedAt: true,
        searchResults: true,
        strainName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Search })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSearch(
    @common.Param() params: SearchWhereUniqueInput,
    @common.Body() data: SearchUpdateInput
  ): Promise<Search | null> {
    try {
      return await this.service.updateSearch({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          searchedAt: true,
          searchResults: true,
          strainName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Search })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSearch(
    @common.Param() params: SearchWhereUniqueInput
  ): Promise<Search | null> {
    try {
      return await this.service.deleteSearch({
        where: params,
        select: {
          createdAt: true,
          id: true,
          searchedAt: true,
          searchResults: true,
          strainName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
